version: '3.9'
services:
  auth:
    build:
      context: ./microservices/auth
    ports:
      - '8001:8000'
  users:
    build:
      context: ./microservices/users
    ports:
      - '8002:8000'
  posts:
    build:
      context: ./microservices/posts
    ports:
      - '8003:8000'
  comments:
    build:
      context: ./microservices/comments
    ports:
      - '8004:8000'
  media:
    build:
      context: ./microservices/media
    ports:
      - '8005:8000'
