backend:
  replicaCount: 1
  image:
    repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.REPLACE_WITH_REGION.amazonaws.com/blog-backend
    tag: main
  autoscaling:
    enabled: false
frontend:
  replicaCount: 1
  image:
    repository: REPLACE_WITH_ACCOUNT_ID.dkr.ecr.REPLACE_WITH_REGION.amazonaws.com/blog-frontend
    tag: main
  autoscaling:
    enabled: false
ingress:
  enabled: false
secretName: blog-app-secrets
